version: "3.8"
services:
 
    db:
        image: mysql
        container_name: db_docker_laravel
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_laravel
        restart: always
        depends_on:
            - db
        ports:
            - 8052:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: maildev_docker_laravel
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8051:80"
        restart: always
        networks:
            - dev

    www:
        build: .
        container_name: www_docker_laravel
        ports:
          - "8050:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev


networks:
    dev:
 
volumes:
    db-data:
